---
title: "How Autistic Children Learn"
description-meta: "Sambhavam is an autism center in BTM layout Bangalore, providing parent guidance, 1 to 1 ABA therapy, speech and occupational therapy. Experienced team, family focused approach."
author: "Chithra Seshadri"
date: "2024-10-30"
categories: [Resources]
---

How do autistic children learn?

Just like other children! 

Why do they go to therapies? 

The stimulation that is to be provided to a child is not available either in schools or homes because of our lifestyles. 

The children seek stimulation, somehow satisfy it one way or the other. For a child who is autistic, seeking attention through verbal or non verbal means becomes challenging. That's when we experience their distress. The children go to therapies to address this distress which arises because of the void between their needs and ability to communicate their needs to their caretakers. 

{{< video show-me-shoulders.mp4 >}}

How do therapists understand children? 

The therapists presume competence, meaning assume the child understands. Lack of communication does not mean lack of knowing. This is the basis for any teaching and connecting to a child. 

When a child does not respond, a therapist does not challenge the child. Instead, holds their hand and facilitates a response by various methods. 

Aggression, negative feedback and punishment is not a part of any therapeutic process. These three are not part of any teaching learning process for any child or person. 

Can this approach be taken at home?

Only when this approach is taken, we will be able to provide a nurture and nourishment needed for the child physically,cognitively, socially and emotionally. 

*Please note that these interventions are shared for general guidance. Designing and executing interventions - more importantly - noticing how the child responds and modifying the interventions so the child does not get distressed, is a specialist job. Consult qualified therapists as necessary.*

::: {.page-cta}

#### Need support for your child?

Get in touch for expert help!

<a href="/contact" class="btn btn-primary">Contact Us</a>

:::