project:
  type: website

website:
  title: "Sambhavam"
  navbar:
    left:
      - admissions/index.qmd
      - people/index.qmd
      - services/index.qmd
      - testimonials/index.qmd
      - join-us/index.qmd
      - contact/index.qmd
      - about/index.qmd

format:
  html:
    theme:
      - cosmo
      - theme.scss
    css: styles.css
    toc: true



