project:
  type: website
  render:
    - "*"
    - "!scripts/*"

website:
  title: "Sambhavam"
  description: "Autism center providing parent guidance, 1 to 1 ABA therapy, speech and occupational therapy. 
    Locations: BTM Layout and Whitefield, Bangalore. Experienced team, family focused approach."
  favicon: /images/sambhavam-logo.png
  open-graph: true
  twitter-card: true
  site-url: https://sambhavam-autism.com/
  navbar:
    background: light
    logo: /images/sambhavam-logo.png
    left:
      - text: "Locations"
        menu: 
          - locations/btm.qmd
          - locations/whitefield.qmd
      - admissions/index.qmd
      - people/index.qmd
      - services/index.qmd
      - testimonials/index.qmd
      - join-us/index.qmd
      - blog/index.qmd
      - gallery/index.qmd
      - contact/index.qmd
      - about/index.qmd
    tools:
      - icon: whatsapp
        href: "https://wa.me/917760764217?text=I%27m+interested+to+know+more+about+Sambhavam."
      - icon: instagram
        href: "https://instagram.com/sambhavam.autism"
      - icon: facebook
        href: https://facebook.com/SambhavamAutism
  page-footer:
    border: true
    left: |
      An initiative of [_Farm Hill Education Trust_](https://farmhill.in).<br>
      Other initiatives [_Farm Hill Learning Community_](https://farmhill-learning.org/) <br>
      and [_Subodha Learning Community_](https://subodha.farmhill.in)

    right:
      - icon: whatsapp
        href: "https://wa.me/917760764217?text=I%27m+interested+to+know+more+about+Sambhavam."
      - icon: instagram
        href: "https://instagram.com/sambhavam.autism"
      - icon: facebook
        href: https://facebook.com/SambhavamAutism


format:
  html:
    theme:
      - cosmo
      - theme.scss
    css: styles.css
    toc: false
    html-math-method: plain



