project:
  type: website

website:
  title: "Sambhavam"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - people/index.qmd
      - about/index.qmd

format:
  html:
    theme:
      - cosmo
      - theme.scss
    css: styles.css
    toc: true



