project:
  type: website

website:
  title: "Sambhavam"
  navbar:
    left:
      - admissions/index.qmd
      - people/index.qmd
      - services/index.qmd
      - testimonials/index.qmd
      - join-us/index.qmd
      - contact/index.qmd
      - about/index.qmd
    tools:
      - icon: whatsapp
        href: "https://wa.me/917760764217?text=I%27m+interested+to+know+more+about+Sambhavam."
      - icon: instagram
        href: "https://instagram.com/sambhavam.autism"
      - icon: facebook
        href: https://facebook.com/SambhavamAutism

format:
  html:
    theme:
      - cosmo
      - theme.scss
    css: styles.css
    toc: true



