---
title: "Admissions"
page-layout: full
---

Sambhavam is focused mainly on early intervention, working with children upto 8 years of age. We think of ourselves as a community of parents and therapists interested in working with children on the spectrum and doing the best we can to improve their quality of life.

## We work with the whole family

At Sambhavam, our focus is on working with the family and not just provide fixed hours of therapy for the child.

As a community of parents and therapists, we understand the pressures felt by families with a child on the spectrum. We believe that parent awareness, and more importantly, parent traning are essential for the child to progress on the path of independence. When the therapies are augmented by the parents at home, the child gets the best help.

We believe that a child should get as much support as she needs, whether in therapy center or in school, for as long as she needs it. It is important that we invest time in building essential skills in a child, rather than try to push her through set levels of achievement. For long term effectiveness, it is important that the parents have a working relationship with the child, so they can continue to support the child.

## Admission process

Our admission process starts with a meeting between the therapy team and the parents. The objective is to understand what the parents are looking for, what the child needs and see if it aligns with what we provide. This may take a couple of hours.

If the parents and the team feel they can work together to provide the necesssary support to the child, we make an offer of admission on email. The offer of admission is accepted by the parents by signing the necessary admission paperwork and paying a modest joining fee.

On the appointed date, the child can start coming to the center. We take a couple of weeks to assess the child thoroughly and develop an IEP. Now the child is a part of the center and we continue to work together! 


::: {.page-cta}

#### Need support for your child?

Get in touch for expert help!

<a href="/contact" class="btn btn-primary">Contact Us</a>

:::