---
title: "Testimonials"
subtitle: People we work with, love us!
page-layout: full
---

::: {.testimonial}

>  Well begun is half done! Good start is important for anything we do. We are satisfied that we started our life journey through autism in Sambhavam. Though we started the intervention service very late for our son, we could see many changes within few days. He could start following instructions, his pointing skills and sitting tolerance was improved. We realized that puzzles is his strength. Though he is still under toilet training, it is much better now. His eating habits were Improved. Thanks to Chithra for her proper guidance given to parents in every small thing in the daily routine. Thanks to Sambhavam team for their kind support. Sambhavam gave us confidence for our future journey. Keep up the good work Chithra and team!

-- Parents of a 4 year old
:::


::: {.testimonial}

>  Sambhavam run by Chithra and Venu was something that we stumbled upon after trying out ABA in quite a few places. What really stuck us at first about Sambhavam was the energy & passion of both Chithra and Venu. Both of them having learnt stuff the hard way, wanted to make it easy for other parents and did not want us to go through all the hardships that they had faced. What we really liked was that it was a full day program unlike the 2 hours slot that others were providing. Some of the things that our son learnt (that he had never learnt it anywhere else) was adherence to schedule, sitting tolerance for up to 6 hours, playing piano, signing, painting craftwork, we were able to control his behavior better (techniques for controlling his behavior were taught to us) and eating food by sitting in one place. A lot of the credit for this has to go to Chithra for making this happen. This was apart from all the academic learnings that were part of the schedule. A very good place for kids on the spectrum and from our own experience very helpful if you get them here as early as possible.

-- Parents of a 5 year old boy
:::

::: {.testimonial}

 > Venu was my colleague from office. He nd Chithra were the ones we turned to when our son was first diagnosed with autism. They have been of tremendous help, support and guidance throughout the last 3 years. We reside in Mumbai and we have been regularly visiting Chithra for periodic assessment and therapy every 6 months. She also provides us with a program and outlines the goals/milestones to be achieved over the next 6 months. We have noticed that unlike most other centres where you have a one size fits all kind of approach; here a lot of care, attention and thought is spared towards each individual. We have seen our son make tremendous progress over these years. Thanks a lot for your care and efforts!

-- Parents of a 6 year old
:::

::: {.testimonial}

>  Our daughter ‘Titli’ is now almost 4 yrs old. She started going to “Sambhavam” from mid January 2016. We opted for ABA therapy because she was unable to communicate her basic needs to us. Through these last 6 months, Titli has started communicating to us through PECS and pointing to objects that she wants. Her understanding of language is now excellent. Her social skills are improving and she has also started imitating very well. We are thankful to Chithra and her team of therapists for their support, hard work, and patience. Above all, what we like most about “Sambhavam”, is their transparency and their willingness to listen to our worries. We know that Chithra is always a call away to help us. We would say that finally we can see our daughter blossoming under their guidance.

-- Parents of Titli
:::